### ISSUE TITLE
Error message when minting/melting invalid tokens

### ISSUE THREAD

**Issue by tuliomir** [HathorNetwork/hathor-wallet-headless#153]
When trying to mint or melt an invalid token, a incorrect error response is returned to the client

For example, when minting, the request:
```sh
curl --location --request POST '{server-host}/wallet/mint-tokens' \
--header 'X-Wallet-Id: {wallet-id}' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'token=invalidToken' \
--data-urlencode 'address={validAddress}' \
--data-urlencode 'amount={validAmount}'
```

Renders a response, with status `200`:
```json
{
    "success": false,
    "error": "Cannot read property 'length' of undefined"
}
```

The expected response should be somewhat similar to what happens when the client does not inform the token at all, or at least descriptive of the actual cause of the error:
```json
{
    "success": false,
    "error": [
        {
            "msg": "Invalid value",
            "param": "token",
            "location": "body"
        }
    ]
}
```

**Comment by prashantpaidi** [comment]
I am new to open source. Can I work on this?

**Comment by D45putspin** [comment]
error is here ```
 const response = await wallet.mintTokens(token, amount, { address, changeAddress });
``` but tbf i found counfuse where this wallet is coming from, is it from lib?

**Comment by D45putspin** [comment]
this can be closed @tuliomir
