### ISSUE TITLE
fix: skipped multisig tests

### ISSUE THREAD

**Issue by tuliomir** [HathorNetwork/hathor-wallet-headless#191]
During #164 , two multisig integration tests failed. Since they were out of the scope of that PR, they were just skipped.
Durint #189, the mulsitsig test on the `start wallet` has also failed and was skipped.

All tests on the multisig mocked and integration suites must pass.

**Comment by r4mmer** [comment]
All tests related to this issue are fixed and have been enabled to run during CI
