### ISSUE TITLE
Get configuration string of tokens

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-headless#223]
# Motivation

Use cases need to share created tokens configuration string with their users, then we must have an easy way to get this information using the headless wallet. Nowadays the use case must go to the explorer to see this data, or create a custom js code.

# Summary

Some options to solve the problem are described below but they must be discussed in more details.

1. Create a new API that receives the token uid and returns the configuration string.
2. In the token creation (and NFT creation) API, return the config string for the created token.

**Comment by tuliomir** [comment]
Closed by #225
