### ISSUE TITLE
bug: create tx proposal using multisig wallet creates a change output for p2pkh

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-headless#230]
### Summary

When using a multisig wallet, the first step to send a transaction is to call `/wallet/p2sh/tx-proposal` with the output you want to send your tokens to. In this API, the wallet headless creates the transaction with inputs/outputs and adds, if needed, another change output for your own wallet.

This step to add the change output is not adding the output `type`, as expected by the serialization method, so when we create the transaction hex to return in the response, the lib is assuming it's a P2PKH output script.

The second step to send a transaction is to decode, check if everything is correct, then sign the tx. In this step the user would already notice that the change address is not from a P2SH wallet. In case the transaction is sent, the change funds will be lost.

#### How to reproduce the error

1. Start a multisig wallet.
2. Create a tx proposal `/wallet/p2sh/tx-proposal` with a small amount, in order to have a change output for you.
3. Get the `txHex` from the response and use the `/wallet/decode` API to see that the change output was created with a P2PKH script.

### Status

The fix is already implemented and some more tests are being made:

https://github.com/HathorNetwork/hathor-wallet-lib/pull/394
https://github.com/HathorNetwork/hathor-wallet-headless/pull/229

**Comment by r4mmer** [comment]
This has been fixed on version [v0.40.3](https://github.com/HathorNetwork/hathor-wallet-lib/releases/tag/v0.40.3) of the wallet-lib and is safe to use starting on version [v0.17.0](https://github.com/HathorNetwork/hathor-wallet-headless/releases/tag/v0.17.0) of the headless.
