### ISSUE TITLE
[Design] external notifications

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet-headless#236]
- Feature Name: Wallet headless external notifications
- Author: Pedro Ferreira <pedro@hathor.network>, André Carneiro <andre.carneiro@hathor.network>

# Summary
[summary]: #summary

A plugin system will be implemented, allowing developers to extend the wallet-headless functionality.
Along with the plugin system a new internal notification service will be created and it will expose events from all started wallets and from the headless itself.
The plugins will have access to the events and can expose them as needed, e.g. sending to a websocket connection, a message queue.

# Motivation
[motivation]: #motivation

The wallet and connection objects emit some events when specific actions happen.
It would be great for some use cases to capture those events and execute some functions, for example it's important to know when a new transaction arrives for the wallet in order to double check a deposit.
If we don't have those event handlers, the use case would need to keep polling the `/tx-history` API to get the latest transactions of the wallet.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

### Events

There are 2 event sources from the started wallets, the `HathorWallet` object itself and the `Connection` from the wallet, each with their own events.

`HathorWallet` events:
- `state`
  - When: the wallet state changes.
  - new event name: `wallet:state`.
  - Extra: will be populated with a human readable state name
- `new-tx`
  - new event name: `wallet:new-tx`.
  - When: a new tx from the wallet arrives.
  - Extra: will be populated with this wallet token balance on the transaction
- `update-tx`
  - new event name: `wallet:update-tx`.
  - When: a tx from the wallet is updated (e.g. being voided)
  - Extra: will be populated with this wallet token balance on the transaction

`Connection` events:
- `state`
  - new event name: `conn:state`.
  - When: the connection state changes.
  - Extra: will be populated with a human readable state name
- `wallet-update`
  - new event name: `conn:wallet-update`.
  - When: a new wallet message arrives.
- `best-block-update`
  - new event name: `conn:best-block-update`.
  - When: a new best block is found.
- `wallet-load-partial-update`
  - new event name: `conn:wallet-load-partial-update`.
  - When: wallet startup, part of wallet tx history is received.

The service will re-emit each event on the "new event name" and on an event called `message`.
The re-emitted event data will have the wallet-id, the name of the event and the original event data.

### Service

The notification service will be a singleton event bus that listens for events on the started wallets and emits them from a single event emitter.

Since the notification bus is an singleton EventEmitter, it can be imported and all event emitter methods will work, e.g. `on`, `once`.

## Plugin system

All plugins will be required to export a method `async init(bus)` that will receive the notification bus.

We will be implementing the following plugins:
- hathor_debug: logs the events on stdout.
  - id: debug
- websocket: runs a websocket server exposing the events.
  - id: ws
- sqs: sends events to sqs messaging queue service.
  - id: sqs
- hathor_rabbitMQ: sends events to a rabbitMQ instance.
  - id: rabbitmq
- hathor_script_runner: run a shell script on every event.
  - id: script

To start a plugin you need to add its plugin id to the array `enabled_plugins` on the config module.

The developer can "install" new plugins by adding modules to the plugin directory and configuring the `plugin_config`.
```js
// config.js
module.exports = {
  //...
  enabled_plugins: ['debug', '<plugin id>'],
  plugins_config: {
    '<plugin id>': {
      name: '<plugin name>',
      file: '<plugin file>',
    }
  },
};
```

Some plugins may require dependencies which will not be installed by default since the plugins are meant as a secondary functionality.
If a user attempts to run a plugin without the required dependencies a custom error will be thrown signaling how to install the required dependencies.

### Plugin: Debug

Each event will be JSON encoded and logged to stdout with `console.log`.
The environment variable `DEBUG_LONG` will be used to determine what to do with long messages (over 1000 characters).

- `all`: will log all messages no matter the size.
- `none`: Do not log long messages.

The default option will log the event type and wallet id if present but any other data will be ommited.
This allows for great debugging information without having too much data on screen.

*Extra config*:
- `HEADLESS_PLUGIN_DEBUG_LONG`: string

### Plugin: Websocket

A websocket server will be started on port 8008 (or on configured port).
All events will be sent to all clients.

If an apikey is configured, it will also be required to connect to the websocket.

*Extra config*:
- `HEADLESS_PLUGIN_WS_PORT`: number, default 8008

### Plugin: SQS

Events will be sent to an SQS queue for processing.
To avoid duplication, only events from the `message` will be sent.

Since aws-sdk allows some freedom in configuring authentication (envvar, credentials file, etc.) we will let it handle authentication.

*Extra config*:
- `HEADLESS_PLUGIN_SQS_URL`: string, required
- AWS credentials

### Plugin: RabbitMQ

Events will be sent to a RabbitMQ queue for processing.
To avoid duplication, only events from the `message` will be sent.

*Extra config*:
- `HEADLESS_PLUGIN_RABBITMQ_URL`: string, required

### Plugin: Script runner

This plugin will create another child process to run an executable or shell script for each message.
To avoid duplication, only events from the `message` will be sent.

The event will be JSON encoded and passed to the script as the first argument.

If the script needs any dependencies to be installed, the developer should create a new container and install these dependencies during build.
The default shell for the headless container is ash since we are running on alpine.

*Extra config*:
- `HEADLESS_PLUGIN_SCRIPT_EXEC`: string

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

## Notification service

The notification service will be a singleton EventEmitter that will re-emit wallet events.

It will have a method `subscribeHathorWallet(walletId, wallet)` to start listening on all wallet events.
This method should be called on all wallets before they are started (to include startup events).

When a wallet is stopped from the API a `wallet:stop` event will be emmited after the wallet has stopped.
No other action is required since the listeners on the wallet events will be deleted along with the wallet object.

### Child process

The NodeJS library [`child_process`](https://nodejs.org/docs/v8.1.4/api/child_process.html) will be used to create a [fork](https://nodejs.org/docs/v8.1.4/api/child_process.html#child_process_child_process_fork_modulepath_args_options) on the application.
The fork will create a child process with an IPC communication channel between processes which we will use to pass events.

The child process is a completely independent process from the parent, except for the IPC communication channel.
This means the notification service on the child process will not receive messages from the parent notification service.
To this end, the child process should listen on the IPC channel for the [`message` event](https://nodejs.org/docs/v8.1.4/api/process.html#process_event_message) and re-emit events on the local notification service.
The parent will be responsible to [send events](https://nodejs.org/docs/v8.1.4/api/child_process.html#child_process_child_send_message_sendhandle_options_callback) to the child process.

Note: Unlike the [fork(2)](https://man7.org/linux/man-pages/man2/fork.2.html) POSIX system call, child_process.fork() does not clone the current process.

### Plugins

The child process will handle plugin startup, importing each enabled plugin and invoking the `init` method injecting the notification service EventEmitter.

The config module will have 2 new configuration options:
- `enabled_plugins`
- `plugin_config`: Only required for custom plugins.

Plugins may want to log to stdout, since the logs may be parsed later we should pipe the stdout to the parent and have the parent log with the configured logger.
```js
// On the parent
child.stdout.on('data', data => {
  // We can process the data if needed.
  console.log(data);
});


// On the child
console.log('foo');
```

The child process will also listen for some other events from the `process`, e.g. `disconnect`, which is emitted when the main process exits or closes the IPC channel.
```js
// On the parent
child.on('disconnect', () => {
  console.log('[ERROR] child process disconnected, exiting...');
  process.exit(127);
});

// On the child
process.on('disconnect', () => {
  process.exit(127);
});
```
Obs: The `console.log` will not work on the child since its stdout is piped to the parent, which has exited.

### Runtime dependency check

The dependencies should be checked before running the plugin, this means they should not be imported at the start of the file since this would not allow us to throw a custom error.

We should import the dependencies with the async `import` and if any errors occurs we should throw an error showing how to install the required dependencies.

```js
try {
  await import('required-module');
} catch (err) {
  throw new Error(`Some plugin dependencies are missing, to install them run:
  $ npm install required-module@1.0.0`);
}
```

This should run for each dependency at the `init` method so the configuration of the plugin only happens if all the required dependencies are met.

# Drawbacks
[drawbacks]: #drawbacks

### No access to HathorWallet objects

Since the plugins are on another process they will not be able to access the wallet objects.

A solution would be using the IPC channel to send requests for the main process and run some actions on the main process.
While this works it will add complexity to this interaction, requiring the implementation of an event driven API for the plugins.

### Spawning another NodeJs process to handle plugins

It is not usually recommended to spawn another process inside a docker container (relevant [docker docs](https://docs.docker.com/engine/reference/run/#foreground)).

Since docker is the expected environment for the wallet-headless we have to expect some issues for handling child processes, the main one is how docker does not send signals (e.g. SIGTERM, SIGINT) to child processes.
Depending on how the child process is created, NodeJS establishes a default handler for the SIGTERM and SIGINT signals to send an `exit` event to the parent (as described [here](https://nodejs.org/docs/v8.1.4/api/child_process.html#child_process_event_exit));

NodeJS also handles sending these signals from the parent to the child, this works well on usual cases but when the process exits without the proper cleanup process it will leave the child process running.
The solution for this is to exit both the main and child processes if one of them disconnects from the shared IPC channel for any reason.
While this works, it will leave the main process vulnerable to any programming errors and untreated errors on the plugins.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

### Side-car container

An alternative to the plugin system on the headless itself is running this system on another docker instance.
The notification service will only export events to this side-car container and the plugins will run on the side-car.

This is a very good alternative to solve the problem of the event loop being locked due to a plugin since the plugin will run on another process/instance (depending on the architecture even another server).

This alternative has virtually no downsides except the extra configuration (another separate container with its own configuration).

#### Event loop may be locked

NodeJS is a single-threaded environment and the main event loop may be locked if the plugin is poorly implemented or introduces a dependency on another system (relevant [NodeJS docs](https://nodejs.dev/en/learn/the-nodejs-event-loop/)).
In the case of the event loop being locked by a plugin the headless API will be unable to respond.

This behavior was confirmed with a plugin that runs the method below on every message to lock the event loop and the headless API became unresponsive.
```js
function pauseFor(ms) {
  const date = new Date();
  let currDate = null;
  do { currDate = new Date(); }
  while (currDate - date < ms);
}
```

The same behavior was tested with an async version of the loop and the event loop was not locked.
```js
async function delay(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}
```

This means that the main event loop will be vulnerable to programming errors from all plugins.

# Prior art
[prior-art]: #prior-art

This design was already in the making on the issue #96.

# Future possibilities
[future-possibilities]: #future-possibilities

Although the main feature is delivering notifications for external apps, the plugin system implemented can have even more impact and possibilities.
We could allow developers to extend the headless API, create routes and handlers, etc.

Only a plugin file with the logic and a simple dockerfile are required to create a custom plugin.
```dockerfile
FROM hathornetwork/hathor-wallet-headless
COPY ./plugin_file.js ./src/plugins/plugin_file.js
```

While not in the scope of this design, a low level server instance can be passed to the child process so that the child can listen on the same port, listen for server events or even create a new API with its own custom paths.
An example would be creating a prometheus route to export data from the wallets.

First we would need to expose the server to the child.

```js
// index.js

import http from 'http';
//...
const server = http.createServer(app);
child.send('server', server);
// Server will later listen on the configured port

// child.js
process.on('message', (data, server) => {
  if (data === 'server') {
    // TODO: use server instance.
  }
});
```

Then plugins would be able to access the http server instance.

**Comment by msbrogli** [comment]
Hi @r4mmer . Nice design! Here are my thoughts:

1) What happens when a plugin process dies? Should we respawn it or ignore it or kill the master process? From your code example, the master process would kill itself.

2) Should we augment the `new-tx` event with a list of deposit or withdrawal information? I mean, the application does not necessarily have a list of addresses, so calculating whether a deposit or a withdrawal occurred might be a complex task.

3) What is the different between a wallet state change and a connection state change? I feel you should provide more information about each event type.

**Comment by r4mmer** [comment]
> What happens when a plugin process dies?

All plugins will run on the same process, if this process dies I believe the master should kill itself to avoid errors on systems that may be listening to the events.

> Should we augment the new-tx event with a list of deposit or withdrawal information?

We can (and should) enrich all events, but I would like to know if there are any info that would be required for the current intended uses.

- `new-tx` and `update-tx`: Token balances of a tx for the wallet
- `state` (both wallet and connection): add human readable connection state names

> What is the different between a wallet state change and a connection state change?

I'll create a small section for each event.

**Comment by pedroferreira1** [comment]
For me the design is already approved, just have some questions:

> Extra config:
> HEADLESS_PLUGIN_DEBUG_LONG: string

How to configure these extra configurations?

> should we have websocket commands so the client can subscribe to the events it wants?

I think we can start with option 3, just send all, and the client can filter by type.

> To avoid duplication, only events from the message will be sent.

I didn't understand this.

> We can (and should) enrich all events, but I would like to know if there are any info that would be required for the current intended uses.
> new-tx and update-tx: Token balances of a tx for the wallet

I feel this could be token balance of the tx for each address, i.e. if 3 of the tx outputs are from addresses of this wallet, then we should show the tx balance for each of these addresses.

**Comment by r4mmer** [comment]
> How to configure these extra configurations?

The wallet-headless has a few ways to be configured, to usual would be a section on `config.js` that the plugin can access.
On docker the configuration is made through envvars and cli arguments (some of which populates the config module).

I will start the child process with the same argv and envvars so that the config.js module is the same as the main process.
So the order of precedence would be `config.js -> cli -> envvar`.

> I didn't understand this.

Sorry, `message` is a channel with all events.
Each event will be sent on 2 channels, one with the name of the event and another with the name `message`.
This is for plugins that are only interested in a type of event, they can listen for that event (e.g. `.on('wallet:new-tx', () => {...})`) or if a plugin want to register different listeners for different events.

So if you listen for `message` and `wallet:new-tx` the new transaction event would be received once for each.
To avoid sending a new transaction event twice to an SQS queue for instance, we only send the `message` channel.

> I feel this could be token balance of the tx for each address, i.e. if 3 of the tx outputs are from addresses of this wallet, then we should show the tx balance for each of these addresses.

Ok, i'll work on this.

**Comment by pedroferreira1** [comment]
@r4mmer thanks for the explanations, I feel they should be in the design as well, not only in this comment.

**Comment by msbrogli** [comment]
> All plugins will run on the same process, if this process dies I believe the master should kill itself to avoid errors on systems that may be listening to the events.

Ok. We might be cautious because it might be a vector for a DoS attack. Kills the plugin and the wallet kills itself. But I agree it might a simple and good solution for now.

> We can (and should) enrich all events, but I would like to know if there are any info that would be required for the current intended uses.
> 
> new-tx and update-tx: Token balances of a tx for the wallet
> state (both wallet and connection): add human readable connection state names
> What is the different between a wallet state change and a connection state change?
> 
> I'll create a small section for each event.

Ok! Thanks!

**Comment by msbrogli** [comment]
@r4mmer This design is approved by me, but I still want to review the details of each event.

**Comment by pedroferreira1** [comment]
✅

**Comment by msbrogli** [comment]
I'd rename the events as follows:

```
Old                              | New
---------------------------------|-----------------------------
wallet:state                     | wallet:state-change
conn:state                       | node:connection-change
conn:wallet-update               | node:wallet-update
conn:best-block-update           | node:best-block-update
conn:wallet-load-partial-update  | wallet:load-partial-update
```

All others remain the same.

The idea behind my suggestion is to (i) standardize the name, adding qualifiers such as `change` and (ii) change the prefix `conn` to `node` to be clear about who generated that event.

I feel that the event `load-partial-update` is generated at the wallet (and not at the full node). Is it correct?

I also feel that we should explain that one does not have to care about the `node:` events, unless in very specific cases. Is that correct?

**Comment by msbrogli** [comment]
Besides my comment about renaming the events, this design is approved to me.

**Comment by r4mmer** [comment]
> I feel that the event load-partial-update is generated at the wallet (and not at the full node). Is it correct?

The event emitter is the `Connection` object which re-emits the `addresses_loaded` event from the fullnode, [ref](https://github.com/HathorNetwork/hathor-wallet-lib/blob/master/src/new/connection.ts#L62-L64).

> I also feel that we should explain that one does not have to care about the node: events, unless in very specific cases. Is that correct?

Yes, I think that the `best-block-update` may have some uses but the others are mostly for debugging the wallet connection.
