### ISSUE TITLE
Request failed with status code 414

### ISSUE THREAD

**Issue by viteshan** [HathorNetwork/hathor-wallet-headless#24]
node version: v12.18.4

After I called the start http, the console reported this error.

1. npm start
2. curl -X POST --data "wallet-id=eee" --data-urlencode "passphrase=123" --data "seedKey=default" http://localhost:8000/start

(node:1346) UnhandledPromiseRejectionWarning: Error: Request failed with status code 414
    at createError (/root/hathor-wallet-headless/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/hathor-wallet-headless/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/hathor-wallet-headless/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by viteshan** [comment]
![image](https://user-images.githubusercontent.com/40378222/94136779-04f6f900-fe98-11ea-93cc-779340cb5f93.png)
![image](https://user-images.githubusercontent.com/40378222/94136811-0d4f3400-fe98-11ea-9d33-324d44e8dc15.png)

**Comment by pedroferreira1** [comment]
Hi @viteshan thanks for the detailed issue. Can you share your `config.js` file without your seeds (please remember to remove your seed words before pasting here)?

**Comment by viteshan** [comment]
![image](https://user-images.githubusercontent.com/40378222/94220256-2ea53400-ff1b-11ea-98ab-8d07bf22cda5.png)

hello @pedroferreira1  this is my `config.js` file.

I copied `server` from the desktop wallet.

**Comment by viteshan** [comment]
I am going to make a docker image for hathor-wallet-headless. I am running the hathor-wallet-headless in this docker container.

```
# Pull base image.
FROM mhart/alpine-node:12.18.4 AS base

RUN apk add --no-cache bash git

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
```

**Comment by pedroferreira1** [comment]
Hi @viteshan did you modify anything on the code, or you are using an unmodified version of the `hathor-wallet-headless` and `hathor-wallet-lib`?

This 414 error means that the server received a GET request with too large URI. Can you try to start again and send here the time you did the test and received the error, so I can debug here?

**Comment by viteshan** [comment]
I do not modify anything on the `hathor-wallet-lib`. Can you add some logs to let me know which uri throw the exception when the error happened?

**Comment by pedroferreira1** [comment]
@viteshan thanks for the feedback. That actually makes sense because we add in the URL params all addresses we are getting the history and each request has at most `GAP_LIMIT` addresses. With the increase of this value, makes the URL too large.

I will close this issue now because the reason for 414 was discovered but will open another one to handle this request with an increased GAP_LIMIT.

Anyway, if you want you can contact me on Discord or Telegram so I can understand better your use case and help you handle this.
