### ISSUE TITLE
scripts not working in container

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-wallet-headless#428]
## Summary

We cannot run the scripts in the final container, we can only run from source code.

## Description

After the Dockerfile was updated to be built in steps, moving only the production dependencies and built code to the final container we introduced an issue running the scripts in the final container.

The best way to run the scripts is with `npm` but it uses `babel-node` a dev dependency that is not included in the container.
We can still run most scripts with `docker run --entrypoint node hathornetwork/hathor-wallet-headless scripts/XXX.js` but scripts that import anything in src will fail due to src not existing on the container. The only script that does it is `create_hsm_wallet` which imports the settings.

### Solution 1

We can just remove babel-node from the npm scripts altogether and use the node directly.
It works for the final container but it adds an extra step to running scripts from the source code, which means we have to build the code with babel first.

This would make any imports to `src` actually be made to `dist` and would enable any script that requires importing methods in the source code.
We would also add more issues to deal with when developing, for instance changing branches and forgetting to re-build the script.

### Solution 2

Add babel-node to the container dependencies and keep source code in final container.
This would make running scripts on the container the same as running when developing, the main issue is that babel-node itself warns us to not use it in production, but it says to not use in production servers due to high memory usage and overheads, but using as a once over interpreter for scripts is very acceptable.

Obs: babel-node adds an additional 17MB to the final container.

### Solution 3

Create 2 sets of commands, one using babel-node and another using node.
This adds more overhead to managing scripts since we need to make sure both commands for the same script work (for instance if one uses a different flag or use the same script) but it avoids the build issues since it uses babel-node locally and avoids adding babel-node as a production dependency.

### Solution 4

Do not use npm as a script runner, we could add something that manages scripts better than npm.
For instance, we could add `just` to the project or rely more on `make`.

**Comment by tuliomir** [comment]
Solution 4 seems to be the most promising. However I could not find what is the `just` package you told about: there are many with this name.

For the `make` reliance, do you already have an idea on how to identify if the code will be run from source or from the built code?

Another idea that occurred to me is that we could refactor the settings in such a way that it could be moved to the root folder, outside both `src` and `dist`. This would also reduce the current risks of circular dependencies we have, but this path may need more research and implementation effort.

**Comment by r4mmer** [comment]
A possible solution I discussed with @pedroferreira1 is a mix of solutions 1 and 4, moving the commands that we want to expose for the user in the container to the Makefile and running with `node ./dist-scripts/XXX.js`, this would enable using imports to the source code (if imported from dist since we are running with node).
Another benefit of this solution would be that we can add some logic to the Makefile so that if we are running locally we can build the code before running the script, this way a local user will not have to manually build the scripts.

**Comment by tuliomir** [comment]
✅ This issue description looks good to me
