### ISSUE TITLE
[Design] UTXO consolidation

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-headless#44]
# Motivation

In some special use cases is really common for a wallet to receive many outputs with a small amount, e.g. a miner wallet (or an exchange). With the current quantity of HTR issued per block, a miner receives 32 HTR each block found. Because of our maximum number of inputs limit of 255, if the miner wants to send more than 8,160 HTR, the transaction would probably fail. Our algorithm to automatically select the inputs is not the best but even with other options, this problem could still happen.

# Solution

## Definition

UTXO consolidation is to combine many utxos into only one in order to reduce the quantity of inputs needed to send a bigger amount. In BTC there are many different aspects to consider when executing a consolidation, especially because of the transaction fees. Because of no fee transactions, it's simpler to do this in HTR.

## Proposal

The solution I would like to propose is simple. Create a POST API in the `wallet-headless` to execute utxo consolidation and a GET API in the `wallet-headless` to manage the utxos. These APIs will call direct methods on `HathorWallet` class to execute the requests.

### POST request (`hathor-wallet-headless`)

**Endpoint**

`/wallet/utxo-consolidation`

**Body parameters**

1. `destination_address (string)`: destination address of the consolidated utxo. Required.
2. `max_utxos (integer)`: maximum number of utxos to aggregate. Not required. Default to MAX_INPUTS (255). I thought about not having this parameter but I think it's good in case the user wants to create smaller transactions with a lower weight, in order to be mined faster.
3. `token (string)`: token to filter the utxos. Not required. If not sent, we select only HTR utxos.
4. `filter_address (string)`: the address to filter the utxos. Not required.
5. `amount_smaller_than (integer)`: maximum limit of utxo amount to filter the utxos list. Not required. We will consolidate only utxos that have an amount lower than this value. Integer representation of decimals, i.e. 100 = 1.00.
6. `amount_bigger_than (integer)`: minimum limit of utxo amount to filter the utxos list. Not required. We will consolidate only utxos that have an amount bigger than this value. Integer representation of decimals, i.e. 100 = 1.00.
7. `maximum_amount (integer)`: limit the maximum total amount to consolidate summing all utxos. Not required. Integer representation of decimals, i.e. 100 = 1.00.

#### Response

1. `success (bool)`: true in case of consolidation success and false otherwise. It might fail in case the user does not have any utxo or if all utxos are locked (thus cannot be transferred).
2. `total_utxos_consolidated (integer)`: count of inputs in the transaction sent (how many utxos were aggregated).
3. `total_amount (integer)`: total amount consolidated.  Integer representation of decimals, i.e. 100 = 1.00.
4. `tx_id (string)`: transaction id of the consolidation tx.
5. `utxos (array)`: array of utxos consolidated. Array of objects `{'address', 'amount', 'tx_id', 'index'}`.

#### Example

```
Request:

$ curl -X POST -H "X-Wallet-Id: {wallet-id}" --data "address=H8bt9nYhUNJHg7szF32CWWi1eB8PyYZnbt" --data "max_utxos=100" http://localhost:8000/wallet/utxo-consolidation

Response:

{
  "success": true,
  "total_utxos_consolidated": 85,
  "tx_id": "00321cf29c369d5fd0b3df3f73fea379792335cc16d43bc6737bd30f462cc402",
  "total_amount": 1000000,
  "utxos": [
    {
      "address": "H8bt9nYhUNJHg7szF32CWWi1eB8PyYZnbt",
      "amount": 900000,
      "tx_id": "001c4eb2e8ddeac442d821eb98c8a7eb29ee2b0a2dbd1dd6d1e3a446cc2a5a9d",
      "index": 0,
    },
    {
      "address": "HAPWcNzhf5wDyh3wtvEgPsnChoMucwX5D2",
      "amount": 100000,
      "tx_id": "0001728de2131cc29e8de34d381ebb6819aeeee82166c5b76e80913ec593a38e",
      "index": 1,
    }
  ]
}

{
  "success": false,
  "message": "No available utxo to consolidate."
}
```

### GET request (`hathor-wallet-headless`)

The idea of this request is to give the wallet owner an overview of the utxos quantity and how they are separated by addresses. The user can run a filter just like in the POST, so it can predict what's gonna happen in the consolidation before executing it.

**Endpoint**

`/wallet/utxo-details`

**Query parameters**

1. `max_utxos (integer)`: maximum number of utxos to aggregate. Not required. Default to MAX_INPUTS (255).
2. `token (string)`: token to filter the utxos. Not required. If not sent, we select only HTR utxos.
3. `filter_address (string)`: the address to filter the utxos. Not required.
4. `amount_smaller_than (integer)`: maximum limit of utxo amount to filter the utxos list. Not required. We will consolidate only utxos that have an amount lower than this value. Integer representation of decimals, i.e. 100 = 1.00.
5. `amount_bigger_than (integer)`: minimum limit of utxo amount to filter the utxos list. Not required. We will consolidate only utxos that have an amount bigger than this value. Integer representation of decimals, i.e. 100 = 1.00.
6. `maximum_amount (integer)`: limit the maximum total amount to consolidate summing all utxos. Not required. Integer representation of decimals, i.e. 100 = 1.00.

#### Response

1. `total_utxos_available (integer)`: total quantity of utxos available
2. `total_utxos_locked (integer)`: total quantity of utxos locked
3. `total_amount_locked (integer)`: total amount locked in this filter. Integer representation of decimals, i.e. 100 = 1.00.
4. `total_amount_available (integer)`: total amount available in this filter. Integer representation of decimals, i.e. 100 = 1.00.
5. `utxos (array)`: Array with utxos. `{'address', 'amount', 'tx_id', 'index', 'locked'}`.

#### Example

```
Request:

$ curl -X GET -H "X-Wallet-Id: {wallet-id}" http://localhost:8000/wallet/utxo-details/

Response:

{
  "total_utxos_available": 2,
  "total_utxos_locked": 0,
  "total_amount_locked": 0,
  "total_amount_available": 1000000,
  "utxos": [
    {
      "address": "H8bt9nYhUNJHg7szF32CWWi1eB8PyYZnbt",
      "amount": 900000,
      "tx_id": "001c4eb2e8ddeac442d821eb98c8a7eb29ee2b0a2dbd1dd6d1e3a446cc2a5a9d",
      "index": 0,
      "locked": false,
    },
    {
      "address": "HAPWcNzhf5wDyh3wtvEgPsnChoMucwX5D2",
      "amount": 100000,
      "tx_id": "0001728de2131cc29e8de34d381ebb6819aeeee82166c5b76e80913ec593a38e",
      "index": 1,
      "locked": false,
    }
  ]
}
```

### Library methods (`hathor-wallet-lib`)

We must create two methods in the `HathorWallet` class (i and ii) and one in the `src/wallet.js` to filter the utxos (iii).

i. `getUtxos(options)`, where `options` is an object with all options from request and will be passed to the `filterUtxos` method.

ii. `consolidateUtxos(destinationAddress, options)`. We should call `filterUtxos` with the `options` as the filter parameter and then create the consolidate transaction with the returned data.

iii. `filterUtxos(options)`, where `options` is an object with all filter options. The first line of the method must unite the object sent with the default values.

```
const filterOptions = Object.assign({
  max_utxos: MAX_INPUTS,
  token: null,
  filter_address: null,
  amount_smaller_than: Infinity,
  amount_bigger_than: 0,
  maximum_amount: 0
}, options);
```

This method is a bit tricky because we currently don't have the utxos saved on storage, we have only all wallet transactions. To create this method with only that, we must iterate through all transactions and check the outputs with `spent_by: null`, this might be slow for bigger wallets. One solution would be to refactor a bit of the storage logic to save the utxos but this is not that simple because this data must be updated in real time as well. 

In my opinion we should start with the solution to iterate through all transactions for now until we have the wallet service, which will make it easier to return utxos faster.

## Tasks

1. Lib: Create method on `HathorWallet` class to get the utxo details of the wallet and to consolidate the utxos.
2. Lib: Create method on `src/wallet` file to filter the utxos.
3. Lib: Create tests utxo details and utxo consolidation.
4. Headless: Create GET endpoint for `utxo-details`.
5. Headless: Create POST endpoint for `utxo-consolidation`.
6. Headless: Add new endpoints to docs.
7. Docs: update headless API docs.

**Estimation**

Some of the tasks above are fast to be done, so it's better to estimate all of them together. I estimate 12h (1,5 days) to finish all of them.

# Q&A

1. We will add support for consolidation only on headless for now, is that ok?
  A: The lib will have the methods but only the facade will have an interface for it. We will implement support only for headless but in the future we can discuss the UI/UX to do it in other wallets.
2. Should we add support to execute the consolidation recursively until we reach only one utxo? This might take a while, then we could start running this manually only.
  A: No, user should do this manually.
3. The GET request requires a lot of processing in the lib if there are many transactions on the wallet. After the wallet-service is released, this request will be really fast. Because of that I think we should not try to optimize it right now.
  A: To improve performance we would need a bigger refactor in current version of wallet lib. Given that this APIs won't be used by many use cases and every moment, we can wait until the release of wallet-service to have an API with improved performance. Otherwise we would waste lot of resources to refactor a code that will be useless in some months.

**Comment by msbrogli** [comment]
I feel the POST `/wallet/utxo-consolidation` should accept more filters. I'd say: (i) filter by address, so one can keep their addresses separate and improve privacy, (ii) filter by amount, so one can skip either big or small amounts from being consolidated, and (iii) add a maximum amount for the consolidated transaction, so it won't create whale addresses and improve privacy.

I also think the response should include list of utxos that was consolidated and the txid of the consolidation transaction.

Finally, in regards to GET `/wallet/utxo-details`, I feel it can be quite an expensive API. So, I think it is worth diving into the low level design of it.

**Comment by msbrogli** [comment]
About the open discussion points:

> 1) We will add support for consolidation only on headless for now.

According to the tasks, the consolidation itself will be implemented in the lib. For now, I think it is enough to have it in the headless wallet. Anyway, we should create issues to implement it in both the desktop and mobile wallets. For those, we need to discuss the UX/UI details.

> 2) The consolidation will be executed only for HTR utxos. Should we add an optional parameter for a token uid, in case the user would like to run a consolidation in another token? Or should we always execute the consolidation in ALL utxos, not filtering by token?

I think this is a necessary filter. I don't know whether we should mix different token uid in consolidation transactions.

> 3) Should we add support to execute the consolidation recursively until we reach only one utxo? This might take a while, then we could start running this manually only.

I don't think it is necessary. The client should do it.

> 4) The GET request requires a lot of processing in the lib if there are many transactions on the wallet. After the wallet-service is released, this request will be really fast. Because of that I think we should not try to optimize it right now.

We should dive into the low level discussion of it. I'm not sure it will be a quick operation in the wallet service. Why would it be?

> 5) Should we add an optional query parameter in the GET endpoint to select a custom token to get the utxo details? For now I think we could have only for HTR.

I just added it to my previous comment.

**Comment by pedroferreira1** [comment]
> I feel the POST /wallet/utxo-consolidation should accept more filters. I'd say: (i) filter by address, so one can keep their addresses separate and improve privacy, (ii) filter by amount, so one can skip either big or small amounts from being consolidated, (iii) filter by token uid (maybe mandatory), and (iv) add a maximum amount for the consolidated transaction, so it won't create whale addresses and improve privacy.
> 
> I also think the response should include list of utxos that was consolidated and the txid of the consolidation transaction. And maybe add the choice to do a dry-run for testing and verification purposes.

I agree with all suggestions. I think the token should not be mandatory, if it's not sent we use HTR, in my opinion. And the dry-run I wouldn't add to this design, don't see as really useful but I might be wrong.

> Finally, in regards to GET /wallet/utxo-details, I feel it can be quite an expensive API. So, I think it is worth diving into the low level design of it. Maybe we should allow the same filters available to the POST /wallet/utxo-consolidation, so users can easily get the details before executing.

I will dive a bit but as I wrote I think we should consider this optimization something we will do after integration with the wallet-service. And I agree with you about the same filters, we should have a single method to filter the utxos and in the case of GET we return them and in the case of POST we consolidate them with a tx.

> We should dive into the low level discussion of it. I'm not sure it will be a quick operation in the wallet service. Why would it be?

In the wallet service we have an utxo table indexed by address. This is a cheap query, different from today that we need to iterate through all localStorage data.

**Comment by pedroferreira1** [comment]
@msbrogli have just updated the design with your comments and some more details. Can you review again please?

**Comment by msbrogli** [comment]
@pedroferreira1 Approved. Just a few comments:

1) I think the proposed filters are enough for now. I think the name and explanation of the filter `address_to_consolidate` is confusing. Maybe `filter_address`?

2) As we have the same filters in the GET method, I agree we can skip the `dry-run` parameter. And I also agree to use the HTR token as default.

3) I agree that we can index later to avoid going through all transactions. Do we have an issue to do it? The best index depends on the filters we will allow. I think an `O(n)` operation might be inevitable.

**Comment by pedroferreira1** [comment]
1. Agreed, updated!
2. 👍 
3. Have an issue for what? I think we won't create this index because the wallet service already has a db table for that. Or are you saying to create an issue on wallet-service to double check the indexes are good for those filters here?
4. Nice suggestion. Just did it.

**Comment by thr0wn** [comment]
@pedroferreira1 Approved. I've just a small note: Adding a locked property for each `utxo` may be helpful.

**Comment by pedroferreira1** [comment]
@thr0wn I agree with your suggestion. I was just thinking about how to add this information.

Should we add just a boolean `locked: true|false`, or separated information about `timelock` and `immature_locked`?

@msbrogli @thr0wn

**Comment by thr0wn** [comment]
@pedroferreira1 I think `locked: true|false` seems enough if we want to keep it more focused on `utxo consolidation`. Additional information would be obtained separately in a [transaction API](https://docs.hathor.network/#operation/transaction).

The use cases that `utxo-details` allows goes beyond the consolidation process, as with all `utxos` in hand (HTR utxos and other tokens utxos) a developer can calculate the token balance, create transactions specifying a custom set of inputs and even do its own consolidation strategy, which gives full programmatic control over balances and transactions. But talking with @pedroferreira1, these use cases may overcomplicate this design, so it can be discussed in other opportunities.

**Comment by msbrogli** [comment]
> @pedroferreira1 Approved. I've just a small note: Adding a locked property for each `utxo` may be helpful.

I didn't understand. Shouldn't we just skip all locked transactions because they cannot be consolidated?

**Comment by msbrogli** [comment]
After discussing with @pedroferreira1, I understood @thr0wn's comment about lock. I agree that we can do it.
