### ISSUE TITLE
balance don't return float/double

### ISSUE THREAD

**Issue by mbnunes** [HathorNetwork/hathor-wallet-headless#83]
Gentlemen, good morning.

I working on my API for unity, I found a possible bug.

When I run:
$ curl -H "X-Wallet-Id: {wallet-id}" http: // localhost: 8000 / wallet / balance
{"available": 499, "locked": 0}

the available always has a whole.
Example: in my wallet there are 4.99 HTRs, the available showed 499.

Is this right?

[PORTUGUESE]
Senhores, bom dia.

Eu trabalhando na minha API para unity, encontrei um possivel bug.

Quando eu executo:
$ curl -H "X-Wallet-Id: {wallet-id}" http://localhost:8000/wallet/balance
{"available":499,"locked":0}

o available sempre manda inteiro. 
Exemplo: na minha wallet tem 4.99 HTRs, o available mostrou 499.

Isso está certo?

**Comment by pedroferreira1** [comment]
Hi @mbnunes the balance API always returns an integer and it's like this by design, it's not a bug. Then if you get `499`, it actually means `4.99`.
