### ISSUE TITLE
Test APIs that changes the wallet balance/history

### ISSUE THREAD

**Issue by thr0wn** [HathorNetwork/hathor-wallet-headless#88]
Some tests require mocking WebSocket messages sent from the full node. When melting tokens, for example, the following happens:

**hathor-wallet-headless** -> POST push_tx                                                                         -> **hathor-core**
**hathor-wallet-headless** <- POST push_tx 200 OK                                                           <- **hathor-core**
**hathor-wallet-headless** <- websocket message with `type: "wallet:address_history"` <- **hathor-core**

Although the PR https://github.com/HathorNetwork/hathor-wallet-headless/pull/69 can handle the push_tx successfully, it does not change the wallet history, so no assertion to verify balance changes can be done. To do so, it is necessary to mock websocket messages with something like [this skipped test](https://github.com/HathorNetwork/hathor-wallet-headless/blob/6d26bd446b4793842d700d85fdffc1043acae24d/__tests__/melt-tokens.test.js#L101). The test was skipped due to not work as expected, but it may help future efforts to test APIs that affect the wallet balance/history.

That said, some strategy to test websocket messages must be done to test the following cases:
1. Assert that `simple-send-tx/send-tx/create-token/mint-token/melt-token` correctly changes the wallet balance.
2. Assert that `/wallet/utxo-consolidation` consolidates utxos without affecting the wallet balance.

**Comment by tuliomir** [comment]
This has been implemented on #149 , #152 and #164
